from enum import IntEnum, IntFlag, auto, unique

import pygame


@unique
class EVENT(IntEnum):

    KEY = auto()
    FOCUS = auto()
    SCHEDULE = auto()


class KEY(IntEnum):
    BACKSPACE = pygame.K_BACKSPACE
    TAB = pygame.K_TAB
    CLEAR = pygame.K_CLEAR
    RETURN = pygame.K_RETURN
    PAUSE = pygame.K_PAUSE
    ESCAPE = pygame.K_ESCAPE
    SPACE = pygame.K_SPACE
    EXCLAIM = pygame.K_EXCLAIM
    QUOTEDBL = pygame.K_QUOTEDBL
    HASH = pygame.K_HASH
    DOLLAR = pygame.K_DOLLAR
    AMPERSAND = pygame.K_AMPERSAND
    QUOTE = pygame.K_QUOTE
    LEFTPAREN = pygame.K_LEFTPAREN
    RIGHTPAREN = pygame.K_RIGHTPAREN
    ASTERISK = pygame.K_ASTERISK
    PLUS = pygame.K_PLUS
    COMMA = pygame.K_COMMA
    MINUS = pygame.K_MINUS
    PERIOD = pygame.K_PERIOD
    SLASH = pygame.K_SLASH
    ZERO = pygame.K_0
    ONE = pygame.K_1
    TWO = pygame.K_2
    THREE = pygame.K_3
    FOUR = pygame.K_4
    FIVE = pygame.K_5
    SIX = pygame.K_6
    SEVEN = pygame.K_7
    EIGHT = pygame.K_8
    NINE = pygame.K_9
    COLON = pygame.K_COLON
    SEMICOLON = pygame.K_SEMICOLON
    LESS = pygame.K_LESS
    EQUALS = pygame.K_EQUALS
    GREATER = pygame.K_GREATER
    QUESTION = pygame.K_QUESTION
    AT = pygame.K_AT
    LEFTBRACKET = pygame.K_LEFTBRACKET
    BACKSLASH = pygame.K_BACKSLASH
    RIGHTBRACKET = pygame.K_RIGHTBRACKET
    CARET = pygame.K_CARET
    UNDERSCORE = pygame.K_UNDERSCORE
    BACKQUOTE = pygame.K_BACKQUOTE
    A = pygame.K_a
    B = pygame.K_b
    C = pygame.K_c
    D = pygame.K_d
    E = pygame.K_e
    F = pygame.K_f
    G = pygame.K_g
    H = pygame.K_h
    I = pygame.K_i  # noqa: E741
    J = pygame.K_j
    K = pygame.K_k
    L = pygame.K_l
    M = pygame.K_m
    N = pygame.K_n
    O = pygame.K_o  # noqa: E741
    P = pygame.K_p
    Q = pygame.K_q
    R = pygame.K_r
    S = pygame.K_s
    T = pygame.K_t
    U = pygame.K_u
    V = pygame.K_v
    W = pygame.K_w
    X = pygame.K_x
    Y = pygame.K_y
    Z = pygame.K_z
    DELETE = pygame.K_DELETE
    KP_0 = pygame.K_KP0
    KP_1 = pygame.K_KP1
    KP_2 = pygame.K_KP2
    KP_3 = pygame.K_KP3
    KP_4 = pygame.K_KP4
    KP_5 = pygame.K_KP5
    KP_6 = pygame.K_KP6
    KP_7 = pygame.K_KP7
    KP_8 = pygame.K_KP8
    KP_9 = pygame.K_KP9
    KP_PERIOD = pygame.K_KP_PERIOD
    KP_DIVIDE = pygame.K_KP_DIVIDE
    KP_MULTIPLY = pygame.K_KP_MULTIPLY
    KP_MINUS = pygame.K_KP_MINUS
    KP_PLUS = pygame.K_KP_PLUS
    KP_ENTER = pygame.K_KP_ENTER
    KP_EQUALS = pygame.K_KP_EQUALS
    UP = pygame.K_UP
    DOWN = pygame.K_DOWN
    RIGHT = pygame.K_RIGHT
    LEFT = pygame.K_LEFT
    INSERT = pygame.K_INSERT
    HOME = pygame.K_HOME
    END = pygame.K_END
    PAGEUP = pygame.K_PAGEUP
    PAGEDOWN = pygame.K_PAGEDOWN
    F1 = pygame.K_F1
    F2 = pygame.K_F2
    F3 = pygame.K_F3
    F4 = pygame.K_F4
    F5 = pygame.K_F5
    F6 = pygame.K_F6
    F7 = pygame.K_F7
    F8 = pygame.K_F8
    F9 = pygame.K_F9
    F10 = pygame.K_F10
    F11 = pygame.K_F11
    F12 = pygame.K_F12
    F13 = pygame.K_F13
    F14 = pygame.K_F14
    F15 = pygame.K_F15
    NUMLOCK = pygame.K_NUMLOCK
    CAPSLOCK = pygame.K_CAPSLOCK
    SCROLLOCK = pygame.K_SCROLLOCK
    RSHIFT = pygame.K_RSHIFT
    LSHIFT = pygame.K_LSHIFT
    RCTRL = pygame.K_RCTRL
    LCTRL = pygame.K_LCTRL
    RALT = pygame.K_RALT
    LALT = pygame.K_LALT
    RMETA = pygame.K_RMETA
    LMETA = pygame.K_LMETA
    LSUPER = pygame.K_LSUPER
    RSUPER = pygame.K_RSUPER
    MODE = pygame.K_MODE
    HELP = pygame.K_HELP
    PRINT = pygame.K_PRINT
    SYSREQ = pygame.K_SYSREQ
    BREAK = pygame.K_BREAK
    MENU = pygame.K_MENU
    POWER = pygame.K_POWER
    EURO = pygame.K_EURO


@unique
class MOD(IntFlag):
    NONE = pygame.KMOD_NONE
    LSHIFT = pygame.KMOD_LSHIFT
    RSHIFT = pygame.KMOD_RSHIFT
    SHIFT = pygame.KMOD_SHIFT
    LCTRL = pygame.KMOD_LCTRL
    RCTRL = pygame.KMOD_RCTRL
    CTRL = pygame.KMOD_CTRL
    LALT = pygame.KMOD_LALT
    RALT = pygame.KMOD_RALT
    ALT = pygame.KMOD_ALT
    LMETA = pygame.KMOD_LMETA
    RMETA = pygame.KMOD_RMETA
    META = pygame.KMOD_META
    CAPS = pygame.KMOD_CAPS
    NUM = pygame.KMOD_NUM
    MODE = pygame.KMOD_MODE
